version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  cassandra:
    image: "cassandra"
    ports:
      - "9042:9042"
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebook_chat
  rabbitmq-stomp:
    image: "jsilvaigor/rabbitmq-stomp"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
