apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: skp-latest
      jib: {}
      context: .
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: Local
deploy:
  kubectl:
    manifests:
      - deployment.yml


    

